package model.module;

import oracle.jbo.server.ApplicationModuleDefImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Sep 07 22:01:31 IST 2017
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class AppModuleAMDefImpl extends ApplicationModuleDefImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public AppModuleAMDefImpl() {
    }
}

