package model.module;
import model.module.common.AppModuleAM;

import oracle.adf.share.ADFContext;

import oracle.jbo.Row;
import oracle.jbo.server.ApplicationModuleImpl;
import oracle.jbo.server.ViewLinkImpl;
import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Sep 07 22:01:30 IST 2017
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class AppModuleAMImpl extends ApplicationModuleImpl implements AppModuleAM {
    /**
     * This is the default constructor (do not remove).
     */
    public AppModuleAMImpl() {
    }

    /**
     * Container's getter for Address1.
     * @return Address1
     */
    public ViewObjectImpl getAddress1() {
        return (ViewObjectImpl) findViewObject("Address1");
    }

    /**
     * Container's getter for Doctor1.
     * @return Doctor1
     */
    public ViewObjectImpl getDoctor1() {
        return (ViewObjectImpl) findViewObject("Doctor1");
    }

    /**
     * Container's getter for Patient1.
     * @return Patient1
     */
    public ViewObjectImpl getPatient1() {
        return (ViewObjectImpl) findViewObject("Patient1");
    }

    /**
     * Container's getter for Doctor2.
     * @return Doctor2
     */
    public ViewObjectImpl getDoctor2() {
        return (ViewObjectImpl) findViewObject("Doctor2");
    }

    /**
     * Container's getter for Patient2.
     * @return Patient2
     */
    public ViewObjectImpl getPatient2() {
        return (ViewObjectImpl) findViewObject("Patient2");
    }

    /**
     * Container's getter for Patient3.
     * @return Patient3
     */
    public ViewObjectImpl getPatient3() {
        return (ViewObjectImpl) findViewObject("Patient3");
    }

    /**
     * Container's getter for Address2.
     * @return Address2
     */
    public ViewObjectImpl getAddress2() {
        return (ViewObjectImpl) findViewObject("Address2");
    }

    /**
     * Container's getter for DoctorFk1VL1.
     * @return DoctorFk1VL1
     */
    public ViewLinkImpl getDoctorFk1VL1() {
        return (ViewLinkImpl) findViewLink("DoctorFk1VL1");
    }

    /**
     * Container's getter for PatientFk1VL1.
     * @return PatientFk1VL1
     */
    public ViewLinkImpl getPatientFk1VL1() {
        return (ViewLinkImpl) findViewLink("PatientFk1VL1");
    }

    /**
     * Container's getter for PatientAddressVL.
     * @return PatientAddressVL
     */
    public ViewLinkImpl getPatientAddressVL() {
        return (ViewLinkImpl) findViewLink("PatientAddressVL");
    }
    
    
    public void initPatientId() {
            ViewObjectImpl vo;
            vo = getPatient3();
            Number patientId = (Number)ADFContext.getCurrent().getSessionScope().get("patientId");
            System.out.println("PatientID : " + patientId);
            vo.setNamedWhereClauseParam("userId", patientId);
            vo.executeQuery();
            ViewObjectImpl vo1;
            vo1 = getCancelledAppointment1();
            vo1.setNamedWhereClauseParam("userId", patientId);
            vo1.executeQuery();
            ViewObjectImpl vo2;
            vo2 = getUpcomingAppointmentPatient1();
            vo2.setNamedWhereClauseParam("userId", patientId);
            vo2.executeQuery();
            ViewObjectImpl vo3;
            vo3 = getUpdateAppointmentPatient1();
            vo3.setNamedWhereClauseParam("userId", patientId);
            vo3.executeQuery();
            ViewObjectImpl vo4;
            vo4 = getMedicalHistory2();
            vo4.setNamedWhereClauseParam("userId", patientId);
            vo4.executeQuery();
        }
    
    public void initDocId() {
            ViewObjectImpl vo;
            vo = getDoctor3();
            Number doctorId = (Number)ADFContext.getCurrent().getSessionScope().get("doctorId");
            System.out.println("DoctorID : " + doctorId);
            vo.setNamedWhereClauseParam("userId", doctorId);
            vo.executeQuery();
            ViewObjectImpl vo1;
            vo1 = getScheduledAppointmentDoctor1();
            vo1.setNamedWhereClauseParam("userId", doctorId);
            vo1.executeQuery();
            ViewObjectImpl vo2;
            vo2 = getPreviousAppointmentDoctor2();
            vo2.setNamedWhereClauseParam("userId", doctorId);
            vo2.executeQuery();
        }
    
    public void initAdminId() {
            ViewObjectImpl vo;
            vo = getAdminVO1();
            System.out.println("hello3");
            Number adminId = (Number)ADFContext.getCurrent().getSessionScope().get("adminId");
            System.out.println("AdminID : " + adminId);
            vo.setNamedWhereClauseParam("userId", adminId);
            vo.executeQuery();
        }
    
    public void initDocPatient() {
            ViewObjectImpl vo;
            vo = getDoctor3();
            Number doctorId = (Number)ADFContext.getCurrent().getPageFlowScope().get("doctorId");
            System.out.println("DoctorID : " + doctorId);
            vo.setNamedWhereClauseParam("userDoctorId", doctorId);
            vo.executeQuery();
        }

    /**
     * Container's getter for DoctorJoinAddress1.
     * @return DoctorJoinAddress1
     */
    public ViewObjectImpl getDoctorJoinAddress1() {
        return (ViewObjectImpl) findViewObject("DoctorJoinAddress1");
    }

    /**
     * Container's getter for Doctor3.
     * @return Doctor3
     */
    public ViewObjectImpl getDoctor3() {
        return (ViewObjectImpl) findViewObject("Doctor3");
    }

    /**
     * Container's getter for Address3.
     * @return Address3
     */
    public ViewObjectImpl getAddress3() {
        return (ViewObjectImpl) findViewObject("Address3");
    }

    /**
     * Container's getter for DoctorAddressVL.
     * @return DoctorAddressVL
     */
    public ViewLinkImpl getDoctorAddressVL() {
        return (ViewLinkImpl) findViewLink("DoctorAddressVL");
    }

    /**
     * Container's getter for SearchAppointmentAvailability1.
     * @return SearchAppointmentAvailability1
     */
    public ViewObjectImpl getSearchAppointmentAvailability1() {
        return (ViewObjectImpl) findViewObject("SearchAppointmentAvailability1");
    }

    /**
     * Container's getter for PatientAuthentication1.
     * @return PatientAuthentication1
     */
    public ViewObjectImpl getPatientAuthentication1() {
        return (ViewObjectImpl) findViewObject("PatientAuthentication1");
    }

    /**
     * Container's getter for UpcomingAppointmentPatient1.
     * @return UpcomingAppointmentPatient1
     */
    public ViewObjectImpl getUpcomingAppointmentPatient1() {
        return (ViewObjectImpl) findViewObject("UpcomingAppointmentPatient1");
    }

    /**
     * Container's getter for UpdateAppointmentPatient1.
     * @return UpdateAppointmentPatient1
     */
    public ViewObjectImpl getUpdateAppointmentPatient1() {
        return (ViewObjectImpl) findViewObject("UpdateAppointmentPatient1");
    }
    
    public String loginAuthentication(String Username, String Password){
            ViewObjectImpl vo;
            vo = getPatientAuthentication1();
            vo.setNamedWhereClauseParam("username", Username);
            vo.setNamedWhereClauseParam("pass", Password);
            vo.executeQuery();
            Row user = vo.first();
            return (user == null ? "" : (String) user.getAttribute(0).toString());
        }
    
    public String loginAuthenticationDoctor(String Username, String Password){
            ViewObjectImpl vo;
            vo = getDoctorAuthenticationVO1();
            vo.setNamedWhereClauseParam("username", Username);
            vo.setNamedWhereClauseParam("pass", Password);
            vo.executeQuery();
            Row user = vo.first();
            return (user == null ? "" : (String) user.getAttribute(0).toString());
        }
    
    public String loginAuthenticationAdmin(String Username, String Password){
            ViewObjectImpl vo;
            vo = getAdminAuthentication1();
            System.out.println("hello2");
            vo.setNamedWhereClauseParam("username", Username);
            vo.setNamedWhereClauseParam("pass", Password);
            vo.executeQuery();
            Row user = vo.first();
            return (user == null ? "" : (String) user.getAttribute(0).toString());
        }

    /**
     * Container's getter for DoctorAuthenticationVO1.
     * @return DoctorAuthenticationVO1
     */
    public ViewObjectImpl getDoctorAuthenticationVO1() {
        return (ViewObjectImpl) findViewObject("DoctorAuthenticationVO1");
    }


    /**
     * Container's getter for AdminAuthentication1.
     * @return AdminAuthentication1
     */
    public ViewObjectImpl getAdminAuthentication1() {
        return (ViewObjectImpl) findViewObject("AdminAuthentication1");
    }

    /**
     * Container's getter for AdminVO2.
     * @return AdminVO2
     */
    public ViewObjectImpl getAdmin1() {
        return (ViewObjectImpl) findViewObject("Admin1");
    }

    /**
     * Container's getter for AdminVO1.
     * @return AdminVO1
     */
    public ViewObjectImpl getAdminVO1() {
        return (ViewObjectImpl) findViewObject("AdminVO1");
    }

    /**
     * Container's getter for AddressVO1.
     * @return AddressVO1
     */
    public ViewObjectImpl getAddressVO1() {
        return (ViewObjectImpl) findViewObject("AddressVO1");
    }

    /**
     * Container's getter for AdminAddressVL1.
     * @return AdminAddressVL1
     */
    public ViewLinkImpl getAdminAddressVL1() {
        return (ViewLinkImpl) findViewLink("AdminAddressVL1");
    }

    /**
     * Container's getter for ScheduledAppointmentDoctor1.
     * @return ScheduledAppointmentDoctor1
     */
    public ViewObjectImpl getScheduledAppointmentDoctor1() {
        return (ViewObjectImpl) findViewObject("ScheduledAppointmentDoctor1");
    }

    /**
     * Container's getter for PreviousAppointmentDoctor1.
     * @return PreviousAppointmentDoctor1
     */
    public ViewObjectImpl getPreviousAppointmentDoctor1() {
        return (ViewObjectImpl) findViewObject("PreviousAppointmentDoctor1");
    }

    /**
     * Container's getter for MedicalConsumption1.
     * @return MedicalConsumption1
     */
    public ViewObjectImpl getMedicalConsumption1() {
        return (ViewObjectImpl) findViewObject("MedicalConsumption1");
    }

    /**
     * Container's getter for ScheduledAppointmentDoctor2.
     * @return ScheduledAppointmentDoctor2
     */
    public ViewObjectImpl getScheduledAppointmentDoctor2() {
        return (ViewObjectImpl) findViewObject("ScheduledAppointmentDoctor2");
    }

    /**
     * Container's getter for MedicalConsumption2.
     * @return MedicalConsumption2
     */
    public ViewObjectImpl getMedicalConsumption2() {
        return (ViewObjectImpl) findViewObject("MedicalConsumption2");
    }

    /**
     * Container's getter for AppointmentToMedicalDoctorVL.
     * @return AppointmentToMedicalDoctorVL
     */
    public ViewLinkImpl getAppointmentToMedicalDoctorVL() {
        return (ViewLinkImpl) findViewLink("AppointmentToMedicalDoctorVL");
    }

    /**
     * Container's getter for LOVMedicalCategory1.
     * @return LOVMedicalCategory1
     */
    public ViewObjectImpl getLOVMedicalCategory1() {
        return (ViewObjectImpl) findViewObject("LOVMedicalCategory1");
    }

    /**
     * Container's getter for PreviousAppointmentDoctor2.
     * @return PreviousAppointmentDoctor2
     */
    public ViewObjectImpl getPreviousAppointmentDoctor2() {
        return (ViewObjectImpl) findViewObject("PreviousAppointmentDoctor2");
    }

    /**
     * Container's getter for MedicalConsumption3.
     * @return MedicalConsumption3
     */
    public ViewObjectImpl getMedicalConsumption3() {
        return (ViewObjectImpl) findViewObject("MedicalConsumption3");
    }

    /**
     * Container's getter for PreviousAppointmentToMedicalDoctorVL.
     * @return PreviousAppointmentToMedicalDoctorVL
     */
    public ViewLinkImpl getPreviousAppointmentToMedicalDoctorVL() {
        return (ViewLinkImpl) findViewLink("PreviousAppointmentToMedicalDoctorVL");
    }

    /**
     * Container's getter for CancelledAppointment1.
     * @return CancelledAppointment1
     */
    public ViewObjectImpl getCancelledAppointment1() {
        return (ViewObjectImpl) findViewObject("CancelledAppointment1");
    }

    /**
     * Container's getter for LOVAppointmentStatus1.
     * @return LOVAppointmentStatus1
     */
    public ViewObjectImpl getLOVAppointmentStatus1() {
        return (ViewObjectImpl) findViewObject("LOVAppointmentStatus1");
    }

    /**
     * Container's getter for MedicalHistory1.
     * @return MedicalHistory1
     */
    public ViewObjectImpl getMedicalHistory1() {
        return (ViewObjectImpl) findViewObject("MedicalHistory1");
    }

    /**
     * Container's getter for MedicalHistory2.
     * @return MedicalHistory2
     */
    public ViewObjectImpl getMedicalHistory2() {
        return (ViewObjectImpl) findViewObject("MedicalHistory2");
    }

    /**
     * Container's getter for MedicalConsumption4.
     * @return MedicalConsumption4
     */
    public ViewObjectImpl getMedicalConsumption4() {
        return (ViewObjectImpl) findViewObject("MedicalConsumption4");
    }

    /**
     * Container's getter for MedicalHistoryMedicalConsumptionVL.
     * @return MedicalHistoryMedicalConsumptionVL
     */
    public ViewLinkImpl getMedicalHistoryMedicalConsumptionVL() {
        return (ViewLinkImpl) findViewLink("MedicalHistoryMedicalConsumptionVL");
    }

    /**
     * Container's getter for AppointmentAvailable1.
     * @return AppointmentAvailable1
     */
    public ViewObjectImpl getAppointmentAvailable1() {
        return (ViewObjectImpl) findViewObject("AppointmentAvailable1");
    }

    /**
     * Container's getter for AppointmentVO1.
     * @return AppointmentVO1
     */
    public ViewObjectImpl getAppointmentVO1() {
        return (ViewObjectImpl) findViewObject("AppointmentVO1");
    }

    /**
     * Container's getter for PatientValidation1.
     * @return PatientValidation1
     */
    public ViewObjectImpl getPatientValidation1() {
        return (ViewObjectImpl) findViewObject("PatientValidation1");
    }

    /**
     * Container's getter for DoctorValidation1.
     * @return DoctorValidation1
     */
    public ViewObjectImpl getDoctorValidation1() {
        return (ViewObjectImpl) findViewObject("DoctorValidation1");
    }

    /**
     * Container's getter for AddressValidation1.
     * @return AddressValidation1
     */
    public ViewObjectImpl getAddressValidation1() {
        return (ViewObjectImpl) findViewObject("AddressValidation1");
    }

    /**
     * Container's getter for InsertPatient1.
     * @return InsertPatient1
     */
    public ViewObjectImpl getInsertPatient1() {
        return (ViewObjectImpl) findViewObject("InsertPatient1");
    }

    /**
     * Container's getter for InsertDoctor1.
     * @return InsertDoctor1
     */
    public ViewObjectImpl getInsertDoctor1() {
        return (ViewObjectImpl) findViewObject("InsertDoctor1");
    }

    /**
     * Container's getter for DoctorRatingValidation1.
     * @return DoctorRatingValidation1
     */
    public ViewObjectImpl getDoctorRatingValidation1() {
        return (ViewObjectImpl) findViewObject("DoctorRatingValidation1");
    }

    /**
     * Container's getter for DoctorRating1.
     * @return DoctorRating1
     */
    public ViewObjectImpl getDoctorRating1() {
        return (ViewObjectImpl) findViewObject("DoctorRating1");
    }

    /**
     * Container's getter for PatientRatingValidation1.
     * @return PatientRatingValidation1
     */
    public ViewObjectImpl getPatientRatingValidation1() {
        return (ViewObjectImpl) findViewObject("PatientRatingValidation1");
    }

    /**
     * Container's getter for PatientRating1.
     * @return PatientRating1
     */
    public ViewObjectImpl getPatientRating1() {
        return (ViewObjectImpl) findViewObject("PatientRating1");
    }

    /**
     * Container's getter for PatientInCity1.
     * @return PatientInCity1
     */
    public ViewObjectImpl getPatientInCity1() {
        return (ViewObjectImpl) findViewObject("PatientInCity1");
    }

    /**
     * Container's getter for DoctorInCity1.
     * @return DoctorInCity1
     */
    public ViewObjectImpl getDoctorInCity1() {
        return (ViewObjectImpl) findViewObject("DoctorInCity1");
    }

    /**
     * Container's getter for AppointmentsRegisteredByDate1.
     * @return AppointmentsRegisteredByDate1
     */
    public ViewObjectImpl getAppointmentsRegisteredByDate1() {
        return (ViewObjectImpl) findViewObject("AppointmentsRegisteredByDate1");
    }

    /**
     * Container's getter for AppointmentByPatient1.
     * @return AppointmentByPatient1
     */
    public ViewObjectImpl getAppointmentByPatient1() {
        return (ViewObjectImpl) findViewObject("AppointmentByPatient1");
    }

    /**
     * Container's getter for AppointmentsByDoctor1.
     * @return AppointmentsByDoctor1
     */
    public ViewObjectImpl getAppointmentsByDoctor1() {
        return (ViewObjectImpl) findViewObject("AppointmentsByDoctor1");
    }
}

