package model.module.common;

import oracle.jbo.ApplicationModule;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Sep 07 22:58:02 IST 2017
// ---------------------------------------------------------------------
public interface AppModuleAM extends ApplicationModule {
    void initPatientId();

    void initDocPatient();

    String loginAuthentication(String Username, String Password);

    String loginAuthenticationDoctor(String Username, String Password);

    void initDocId();

    void initAdminId();

    String loginAuthenticationAdmin(String Username, String Password);
}

